import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";
import "./globals.css";
import Header from "../components/common/Header";
import LayoutWrapper from "@/components/common/LayoutWrapper";
import Footer from "@/components/common/Footer";
import { ThemeProvider } from "next-themes";
import { UserProvider } from "@/provider/UserContext";
import { Toaster } from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const header = <Header />;
  const footer = <Footer />;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <UserProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <LayoutWrapper header={header} footer={footer}>
              <main className="flex-grow container min-w-full">{children}</main>
            </LayoutWrapper>
          </ThemeProvider>
          <Toaster />
        </UserProvider>
      </body>
    </html>
  );
}
